treeTester.exe: htree.cc treeTest.cc
	g++ -g -Wall -Wextra -pedantic -Werror treeTest.cc htree.cc -o treeTester.exe
clear:
	clear
	clear
andshake:
	clear
	clear
	g++ -g -Wall -Wextra -pedantic -Werror treeTest.cc htree.cc -o treeTester.exe
	echo fart

